name: Full-Stack CI with Maven and React

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Backend with Maven
      working-directory: ./backend  # Adjust the path to your backend directory
      run: mvn -B package --file pom.xml

    - name: Run Backend Tests
      working-directory: ./backend
      run: mvn test

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you need

    - name: Install Frontend Dependencies
      working-directory: ./frontend  # Adjust the path to your frontend directory
      run: npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: npm run build

    # Optional: Deploy step
    # - name: Deploy Application
    #   run: |
    #     # Add your deployment commands here
